[package]
name = "imxrt1020evk_fcb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imxrt-boot-gen = { path = "../../imxrt-boot-gen", features = ["imxrt1020"] }
